# -------- Model / Device --------
model:
  model_name: mistralai/Mistral-7B-Instruct-v0.2
  device: cuda:0         
  dtype: auto 
  gpu_mem_util: 0.5

# -------- Retrieval (RAGatouille / ColBERT) --------
retrieval:
  model_id: colbert-ir/colbertv2.0
  dataset_name: pipeline_dataset
  r_text_index_key: r_text_index
  doc_key: doc_id
  question_key: question
  retrieved_key: retrieved_indices
  page_id_key: page_ids
  top_k: 5                 # top-k retrieval per sample

# -------- Prefill Mode --------
# Choose ONE of: full_kv_reuse | cb_fuse | recompute
prefill:
  mode: full_kv_reuse      
  cb:                        
    prefix_prompt: >
      You will be asked a question after reading several passages.
      Please directly answer the question based on the given passages.
      Do NOT repeat the question. The answer should be within 5 words..
      Passages:
    query_prompt: >
      Answer the question directly based on the given passages.
      Do NOT repeat the question. The answer should be within 5 words.
      Question:
    max_new_tokens: 128

# -------- Cache limits & memory budgets --------
cache:
  max_gpu_chunks: 5
  max_cpu_chunks: 1000
  gpu_memory_limit_gb: 40.0
  cpu_memory_limit_gb: 100.0

# -------- KV builder (prefill & placeholders) --------
kv_builder:
  max_samples: 0           # 0 = all
  dump_placements: true
  save_cache_dir: kv_caches      
  save_placeholders: false

# -------- Speculative predictor --------
speculative:
  top_k: 5                
  steps: 16
  promote_per_step: 2
  max_gpu: 5
  max_samples: 0           # 0 = all
  enable_progress: false
  out_path: speculative_next.json   

# -------- Scheduler (TANGO) --------
scheduler:
  max_gpu: 5
  step_duration_ms: 50
  safety_margin_ms: 30
  max_samples: 0           # 0 = all
  load_cache_dir: kv_caches      # directory containing on-disk KV (from kv_builder)
  cache_filter_prefix: auto              # "auto" => f"{sample_id}_chunk"
  load_initial_to_gpu: true             # if true, immediately promote preloaded CPU entries
  enable_progress: false
  out_path: scheduler/decoder_trace.json

# -------- Paths (artifacts written under the main --output dir) --------
paths:
  retrieval_json: retrieval/rag_output.json
  kv_summary_json: kv_build/kv_cache_summary.json
